---

- name: playbook to demonstrate how to remove a package from hosts
  hosts: all
  become: yes


  tasks:
    - name: remove apache from the hosts servers
      ansible.builtin.dnf:
        name: httpd
        state: absent


    - name: remove php from the hosts servers
      ansible.builtin.dnf:
        name: php
        state: absent
